# Generated by Django 3.1.3 on 2020-11-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebank',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='CompanyAccount',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeBank',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
