# Generated by Django 3.1.3 on 2020-11-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20201125_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company_id',
        ),
    ]
